[functions]
    directory = "netlify/functions"

[[redirects]]
    from = "/api/cities"
    to = "/.netlify/functions/handler"
    status = 200

[[redirects]]
    from = "/api/cities/*"
    to = "/.netlify/functions/handler"
    status = 200