[[redirects]]
    from = "/api/cities"
    to = "/.netlify/functions/getCities"
    status = 200
    conditions = { method = ["GET"] }

[[redirects]]
    from = "/api/cities"
    to = "/.netlify/functions/addCity"
    status = 200
    conditions = { method = ["POST"] }

[[redirects]]
    from = "/api/cities/:id"
    to = "/.netlify/functions/getCities"
    status = 200
    conditions = { method = ["GET"] }

[[redirects]]
    from = "/api/cities/:id"
    to = "/.netlify/functions/deleteCity"
    status = 200
    conditions = { method = ["DELETE"] }